CREATE TABLE AIR_NAME (
  AIR_AIR_CODE  VARCHAR(20) NOT NULL COMMENT '비행기넘버',
  AIR_AIR_NAME  VARCHAR(20) NOT NULL COMMENT '비행기종류(이름)',
  PRIMARY KEY(AIR_AIR_CODE)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8
COMMENT = '비행기 관리 테이블'
;

CREATE TABLE AIR_RV (
  AIR_RV_IDX INT NOT NULL AUTO_INCREMENT COMMENT '번호',
  AIR_AIR_CODE  VARCHAR(20) NOT NULL COMMENT '비행기넘버',
  AIR_RV_DEP  VARCHAR(20) NOT NULL COMMENT '출발지역',
  AIR_RV_ARR  VARCHAR(20) NOT NULL COMMENT '도착지역',
  AIR_RV_DAY  VARCHAR(20) NOT NULL COMMENT '날짜',
  AIR_RV_TIME  VARCHAR(20) NOT NULL COMMENT '비행시간',
  AIR_RV_FS  INT NOT NULL COMMENT '퍼스트 클래스 좌석수',
  AIR_RV_BS  INT NOT NULL COMMENT '비지니스 클래스 좌석수',
  AIR_RV_ES  INT NOT NULL COMMENT '이코노미 클래스 좌석수',
  AIR_RV_FP  INT NOT NULL COMMENT '퍼스트 클래스 가격',
  AIR_RV_BP  INT NOT NULL COMMENT '비지니스 클래스 가격',
  AIR_RV_EP  INT NOT NULL COMMENT '이코노미 클래스 가격',
  PRIMARY KEY(AIR_RV_IDX),
  foreign key(AIR_AIR_CODE) references AIR_NAME(AIR_AIR_CODE) on update cascade on delete restrict
)
ENGINE=InnoDB DEFAULT CHARSET=utf8
COMMENT = '비행편 관리 테이블'
;

CREATE TABLE AIR_ORDER(
  AIR_ORDER_IDX INT NOT NULL AUTO_INCREMENT COMMENT '번호',
  AIR_RV_IDX INT COMMENT '비행편번호',
  AIR_AIR_CODE  VARCHAR(20) NOT NULL COMMENT '비행기넘버',
  AIR_USER_MID VARCHAR(20) NOT NULL COMMENT '회원 아이디',
  AIR_RV_DEP  VARCHAR(20) DEFAULT NULL COMMENT '출발지역',
  AIR_RV_ARR  VARCHAR(20) DEFAULT NULL COMMENT '도착지역',
  AIR_RV_GO  VARCHAR(20) NOT NULL COMMENT '가는날짜',
  AIR_RV_BACK  VARCHAR(20) DEFAULT NULL COMMENT '오는날짜',
  AIR_RV_TIME  VARCHAR(20) DEFAULT NULL COMMENT '비행시간',
  AIR_ORDER_WAY  INT NOT NULL COMMENT '편도왕복',
  AIR_ORDER_FC  INT DEFAULT 0 COMMENT '퍼스트 클래스',
  AIR_ORDER_BC  INT DEFAULT 0 COMMENT '비지니스 클래스',
  AIR_ORDER_EC  INT DEFAULT 0 COMMENT '이코노미 클래스',
  AIR_RV_PP  INT NOT NULL COMMENT '주문가격',
  PRIMARY KEY(AIR_ORDER_IDX),
  foreign key(AIR_RV_IDX) references AIR_RV(AIR_RV_IDX) on update cascade on delete restrict
)
ENGINE=InnoDB DEFAULT CHARSET=utf8
COMMENT = '비행편 주문 테이블'
;
