CREATE TABLE AIR_USER(
		AIR_USER_IDX INT NOT NULL AUTO_INCREMENT COMMENT '회원 번호', 
    AIR_USER_MID VARCHAR(20) NOT NULL COMMENT '회원 아이디',
    AIR_USER_PWD VARCHAR(100) NOT NULL COMMENT '회원 비밀번호',
		AIR_USER_NAME VARCHAR(20) NOT NULL COMMENT '회원 이름',
    AIR_USER_BIRTH CHAR(10) NOT NULL COMMENT '생년월일',
    AIR_USER_NUMBER CHAR(15) NOT NULL COMMENT '회원 전화번호',
    AIR_USER_EMAIL VARCHAR(50) NOT NULL COMMENT '이메일',
    AIR_USER_ADDRESS VARCHAR(50) DEFAULT NULL COMMENT '회원 주소',
    AIR_USER_DEL CHAR(2) DEFAULT 'NO' COMMENT '회원탈퇴 여부 (OK:탈퇴신청, NO:가입중)',
    AIR_USER_POINT INT DEFAULT 3000 COMMENT '포인트 최초가입 3000',
    AIR_USER_LEVEL INT NOT NULL DEFAULT 4 COMMENT '회원 등급',
    AIR_USER_VISITCNT INT DEFAULT 0 COMMENT '방문 횟수',
    PRIMARY KEY (AIR_USER_IDX,AIR_USER_MID)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8
COMMENT = '회원 정보 테이블'
;
